IssueComment
  { issueCommentUpdatedAt = 2016 (-04) (-27) 19 : 33 : 23 UTC
  , issueCommentUser =
      SimpleUser
        { simpleUserId = Id 7431361
        , simpleUserLogin = N "larkost"
        , simpleUserAvatarUrl =
            "https://avatars.githubusercontent.com/u/7431361?v=3"
        , simpleUserUrl = "https://api.github.com/users/larkost"
        , simpleUserType = OwnerUser
        }
  , issueCommentUrl =
      "https://api.github.com/repos/rethinkdb/rethinkdb/issues/comments/215201842"
  , issueCommentHtmlUrl =
      "https://github.com/rethinkdb/rethinkdb/issues/5694#issuecomment-215201842"
  , issueCommentCreatedAt = 2016 (-04) (-27) 19 : 27 : 42 UTC
  , issueCommentBody =
      "This has been merged into `next` with df57248c (and `v2.3.x` in 979600e7) after CR 3608 from branch `larkost/5147-python-driver-utils`."
  , issueCommentId = 215201842
  }