IssueComment
  { issueCommentUpdatedAt = 2014 (-08) (-08) 23 : 13 : 22 UTC
  , issueCommentUser =
      SimpleUser
        { simpleUserId = Id 7431361
        , simpleUserLogin = N "larkost"
        , simpleUserAvatarUrl =
            "https://avatars.githubusercontent.com/u/7431361?v=3"
        , simpleUserUrl = "https://api.github.com/users/larkost"
        , simpleUserType = OwnerUser
        }
  , issueCommentUrl =
      "https://api.github.com/repos/rethinkdb/rethinkdb/issues/comments/51667855"
  , issueCommentHtmlUrl =
      "https://github.com/rethinkdb/rethinkdb/issues/2822#issuecomment-51667855"
  , issueCommentCreatedAt = 2014 (-08) (-08) 23 : 13 : 22 UTC
  , issueCommentBody =
      "The solution was to remove everything for the rethinkdb package from sys.modules (including all of the sub-modules), as well as removing a few package-references from the driver (e.g.: docs.py had `import rethinkdb`). This is up for review in CR 1918, and the branch is `larkost/2822-import_python_driver-fix-v2`."
  , issueCommentId = 51667855
  }