IssueComment
  { issueCommentUpdatedAt = 2013 (-08) (-19) 23 : 40 : 28 UTC
  , issueCommentUser =
      SimpleUser
        { simpleUserId = Id 706854
        , simpleUserLogin = N "AtnNn"
        , simpleUserAvatarUrl =
            "https://avatars.githubusercontent.com/u/706854?v=3"
        , simpleUserUrl = "https://api.github.com/users/AtnNn"
        , simpleUserType = OwnerUser
        }
  , issueCommentUrl =
      "https://api.github.com/repos/rethinkdb/rethinkdb/issues/comments/22912922"
  , issueCommentHtmlUrl =
      "https://github.com/rethinkdb/rethinkdb/issues/1322#issuecomment-22912922"
  , issueCommentCreatedAt = 2013 (-08) (-19) 23 : 40 : 28 UTC
  , issueCommentBody =
      "I thought that Python retried interrupted system calls automatically, and did not exposes EINTR."
  , issueCommentId = 22912922
  }