IssueComment
  { issueCommentUpdatedAt = 2013 (-08) (-16) 03 : 56 : 31 UTC
  , issueCommentUser =
      SimpleUser
        { simpleUserId = Id 43867
        , simpleUserLogin = N "jdoliner"
        , simpleUserAvatarUrl =
            "https://avatars.githubusercontent.com/u/43867?v=3"
        , simpleUserUrl = "https://api.github.com/users/jdoliner"
        , simpleUserType = OwnerUser
        }
  , issueCommentUrl =
      "https://api.github.com/repos/rethinkdb/rethinkdb/issues/comments/22746370"
  , issueCommentHtmlUrl =
      "https://github.com/rethinkdb/rethinkdb/issues/1304#issuecomment-22746370"
  , issueCommentCreatedAt = 2013 (-08) (-16) 03 : 56 : 31 UTC
  , issueCommentBody =
      "Just to clarify I meant the fact that it says \"Successfully Passed py tests\" when a test failed is silly reporting."
  , issueCommentId = 22746370
  }