IssueComment
  { issueCommentUpdatedAt = 2015 (-04) (-02) 19 : 20 : 32 UTC
  , issueCommentUser =
      SimpleUser
        { simpleUserId = Id 552910
        , simpleUserLogin = N "Tryneus"
        , simpleUserAvatarUrl =
            "https://avatars.githubusercontent.com/u/552910?v=3"
        , simpleUserUrl = "https://api.github.com/users/Tryneus"
        , simpleUserType = OwnerUser
        }
  , issueCommentUrl =
      "https://api.github.com/repos/rethinkdb/rethinkdb/issues/comments/89015247"
  , issueCommentHtmlUrl =
      "https://github.com/rethinkdb/rethinkdb/issues/4005#issuecomment-89015247"
  , issueCommentCreatedAt = 2015 (-04) (-02) 19 : 20 : 32 UTC
  , issueCommentBody =
      "The fix has been approved and merged to `next` in commit 5980b97, cherry-picked to `v2.0.x` in commit be44d3c, and cherry-picked into `v1.16.x` in commit 3cdf918.  Will be in release 2.0 unless we do a python driver release for this."
  , issueCommentId = 89015247
  }